README.md
tekton/build-image.yaml
tekton/deploy.yaml
tekton/gitops.yaml
tekton/health-check.yaml
tekton/js-test.yaml

Add tekton tasks to be use by the pipelines

---

terraform/scripts/acp

Just rearranging the code to make it more readable. No (intended) changes to implementation.

Script cleanup

---

terraform/scripts/acp-admin
terraform/scripts/kill-kube-ns

In acp-admin, added links to docs
In kill-kube-ns, added a usage message

Script improvements

---

terraform/stages-crc/stage2-sonarqube.tf
terraform/stages-ocp4/stage2-sonarqube.tf

use default name for postgress dbname

---

README.md

Tekton is supported - and strategic - so we should mention it. I've also corrected a couple of typos.

Include Tekton as well as Jenkins in tooling list

---

terraform/scripts/acp-users

Changed one word in the usage line so that it matches the new filename.

Rename acp-dev to acp-users

---

terraform/scripts/acp-acct
terraform/scripts/acp-admin

Three scripts:
- acp-acct -- Account Administrators access policy
- acp-admin -- Environment Administrators access policy
- acp-user -- Environment Users access policy
More testing, more fixes.

Access groups

---

terraform/scripts/tools.yaml

Update tool references to fix navigation

Update tool references to fix navigation

---

terraform/scripts/acp-admin.sh
terraform/scripts/acp-mgr-iaas.sh
terraform/scripts/acp-user.sh

Fixed the fix I made last week. Also updated some comments.

Another fix for bug to see group in resource list

---

terraform/scripts/acp-iaas.sh

In addition to the role needed to set an API key, include the roles the key will need for IKS to create a cluster.

Add more create cluster roles

---

terraform/runTerraform.sh

- Adds logic to check for existing workspace directory and prompt user
- Adds --delete and --keep flags to avoid the workspace prompt
- Renames --force arg to --auto-approve to be consistent with terraform flags
ibm-garage-cloud/planning#384

Updates runTerraform script

---

terraform/settings/environment.tfvars

- Adds vpc_cluster flag
- Adds logdna_exists flag
- Adds sysdig_exists flag

Updates default environment.tfvars

---

terraform/settings/environment.tfvars
terraform/stages/stage3-logdna.tf
terraform/stages/variables.tf

- Adds logdna_name variable in variables.tf
- Updates stage3-logdna to use the logdna_name variable
- Adds logdna_name and documentation to environment.tfvars
ibm-garage-cloud/planning#249

Updates for LogDNA configuration

---

terraform/settings/environment.tfvars
terraform/stages/stage3-sysdig.tf
terraform/stages/variables.tf

- Adds sysdig_name variable
- Updates stage3-sysdig to use the sysdig_name variable
- Adds sysdig_name to environment.tfvars with documentation
ibm-garage-cloud/planning#250

Updates Sysdig configuration

---

terraform/stages/stage2-jaeger.tf

- Adds agent and endpoint config to jaeger-config configmap

Updates jaeger stage to v1.6.0

---

.github/scripts/update-modules.sh
.github/workflows/create-pr.yaml
.github/workflows/verify.yaml
terraform/stages/stage2-artifactory.tf
terraform/stages/stage2-jenkins.tf
terraform/stages/stage3-sysdig.tf

- Adds a pipeline to update the module versions when a repository_dispatch event is received (the modules will be updated to post the event when a new release is created)

Module refresh

---

launch.sh

Change docker image version in launch.sh to use image with IBM Terraform provider version 1.7.1

update docker image version

---

.github/workflows/verify.yaml
terraform/settings/environment.tfvars
terraform/stages/stage1-cluster.tf
terraform/stages/variables.tf

- Exposes the registry_namespace variable on the container-provider
- Adds documentation in environment.tfvars

Adds field for registry namespace

---

.github/workflows/notify.yaml
.github/workflows/verify-pr.yaml

- Verify PR has an issue in the if condition
- The notify pipeline does not trigger when a release is published

Pipeline fixes

---

.github/scripts/update-modules.sh

- Adds -e flag to fix sed in-place update command

Updates update-modules.sh

---

.tile/docs/README.md
.tile/scripts/build.sh
.tile/scripts/master.json

- Fixes the path in the generated offering tar file
- Updates the variable descriptions in the tile README and in the offering json

Updates the tile build process

---

.github/workflows/notify-slack.yaml

- Remove the ref, event, and actions url from the slack message

Sets MSG_MINIMAL on slack notification to remove noise

---

terraform/stages/stage1-cluster.tf

- Picks up fix for registry-namespace in ibmcloud ConfigMap
ibm-garage-cloud/planning#451

Bumps container-platform module to v1.11.3

---

terraform/stages/stage2-dashboard.tf

- Contains improved module verification pipeline

Bumps dashboard module to v1.4.1

---

terraform/stages/stage2-swagger.tf

- Contains updated pipeline to validate ConsoleLink

Bumps swaggereditor module to v1.3.1

---

terraform/stages/stage2-sonarqube.tf

- Fixes bug to create ConsoleLink for OpenShift 4.3

Bumps sonarqube module to v1.5.3

---

terraform/stages/stage2-artifactory.tf

- Includes test to verify support for OCP 4.4

Bumps artifactory module to v1.5.0

---

.github/workflows/notify-slack.yaml
.github/workflows/verify-pr.yaml

- Adds ocp44_vpc to test matrix
- Updates slack notification message

OpenShift 4.4 vpc validation

---

terraform/stages/stage2-sonarqube.tf

- Updates plugin versions
- Adds github plugin

Bumps sonarqube module to v1.6.0

---

terraform/stages/stage2-tekton.tf

- Reverts to openshift-pipeline from community source for now

Bumps tekton module to v1.4.3

---

terraform/stages/stage2-tekton.tf

- Verifies deployment on ocp 4.4

Bumps tekton-resources module to v1.2.1

---

terraform/stages/stage2-sonarqube.tf

ibm-garage-cloud/ibm-garage-iteration-zero#135

Reverts sonarqube module to v1.5.3 to fix issue

---

terraform/stages/stage2-tekton.tf

- Fixes timing issue with creation of .tmp folder
ibm-garage-cloud/planning#453

Bumps tekton-resources to v1.2.2

---

terraform/stages/stage1-cluster.tf
terraform/stages/stage2-artifactory.tf
terraform/stages/stage2-dashboard.tf
terraform/stages/stage2-sonarqube.tf
terraform/stages/stage3-logdna.tf
terraform/stages/stage3-sysdig.tf

- Updates components to create console link with correct icons

Console link update

---

.tile/scripts/master.json
terraform/settings/environment.tfvars
terraform/stages/variables.tf

- Updates variable names and documentation in environment.tfvars
- Adds provision_logdna and provision_sysdig (as well as fixes typo in sysdig_name description) in master.json

Updates for LogDNA and Sysdig

---

terraform/scripts/add-user.sh
terraform/scripts/rbac-roles.yaml

- Updates rbac yaml to create a group and add it to the rbac roles
- Adds `add-user.sh` script to add a user to the created group

RBAC script updates

---

terraform/stages/stage2-tekton.tf

- Updates the version to v1.2.3 to pin the version of tekton tasks installed

Sets tekton-resources to v1.2.3

---

terraform/stages/stage2-artifactory.tf

- Automates post-install configuration steps
- Sets internal (service) url in secret

Artifactory automated setup v1.9.0

---

terraform/stages/stage1-namespaces.tf
terraform/stages/stage2-tekton.tf

- Updates automated setup of Artifactory to create the config properly
- Updates the namespace module to copy config for other tools
- Updates the tekton module to set the url properly in the configmap

Updates for tekton, artifactory, and namespace

---

terraform/stages/stage3-logdna.tf
terraform/stages/stage3-sysdig.tf

- Picks up new `tools_namespace` variable to create tool-config in correct namespace
ibm-garage-cloud/planning#499

Bumps logdna and sysdig modules to v2.2.0

---

terraform/stages-ocp4/stage2-dashboard.tf
terraform/stages/stage2-dashboard.tf
terraform/stages/variables.tf

- Bumps dashboard module to v1.8.0
- Changes default values for provision_logdna and provision_sysdig to 'true'

Updates variables and dashboard module

---

terraform/stages/stage2-argocd.tf

- Bumps argocd module to v2.9.0
- Installs key-protect plugin

Adds support for Key Protect secret management

---

terraform/stages-ocp4/stage2-tekton.tf
terraform/stages/stage2-tekton.tf

remove unused tekton namespace

---

.tile/tiles/cloudnative-toolkit-all-in-one/offering.json
.tile/tiles/cloudnative-toolkit/offering.json
.tile/tiles/cluster-classic/offering.json
.tile/tiles/cluster-vpc/offering.json

- Fixes default values for offering variables
- Adds cos variables for vpc cluster tile

Updates tile offering configuration

---

terraform/stages-cluster/stage1-cluster.tf
terraform/stages/stage1-cluster.tf

ibm-garage-cloud/terraform-ibm-container-platform#e44afe07215f66a90c977a7346a28b0cac9ef9df

Updates ibm-garage-cloud/terraform-ibm-container-platform module to v1.19.1

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton-resources#c82da6cba0f821e6d6c869f3ef2280660260c3c1

Updates ibm-garage-cloud/terraform-tools-tekton-resources module to v2.2.1

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton-resources#555be8f6da9c8339e71237f1c1adbd5518ab018c

Updates ibm-garage-cloud/terraform-tools-tekton-resources module to v2.2.2

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton-resources#b0e667f3fe2f3add09699cae6448a8bf62f4cba7

Updates ibm-garage-cloud/terraform-tools-tekton-resources module to v2.2.3

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton-resources#a61c40aabba9cf59168af0128937eb26e2305ed4

Updates ibm-garage-cloud/terraform-tools-tekton-resources module to v2.2.4

---

.tile/tiles/cluster-classic/offering.json
.tile/tiles/cluster-vpc/offering.json

fix machine flavor

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

ibm-garage-cloud/terraform-ibm-image-registry#2bd96e522b9514e8ee3a9ed76c5e1e0bdd218afe

Updates ibm-garage-cloud/terraform-ibm-image-registry module to v1.3.0

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton-resources#9a429342c1c242c5855ee5e392ba91b0413000d3

Updates ibm-garage-cloud/terraform-tools-tekton-resources module to v2.2.5

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton#9ddc1790736d4b331716055923b6f0f140f3a5ab

Updates ibm-garage-cloud/terraform-tools-tekton module to v2.1.0

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

ibm-garage-cloud/terraform-ibm-image-registry#327e712123f6ecbd1441a734be671789cae3e3d2

Updates ibm-garage-cloud/terraform-ibm-image-registry module to v1.3.1

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

ibm-garage-cloud/terraform-ibm-image-registry#6286f363690dabb2edbcbcbfc8fb2bb5b565e3c0

Updates ibm-garage-cloud/terraform-ibm-image-registry module to v1.3.2

---

install/install-ibm-toolkit.sh

move install script from guide to here

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton-resources#b7f885dbca257b0ac846871c2a9028a6f0d90451

Updates ibm-garage-cloud/terraform-tools-tekton-resources module to v2.2.6

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton-resources#70c5b05706c51d2f18df02f5e1ac84febdf3b1b3

Updates ibm-garage-cloud/terraform-tools-tekton-resources module to v2.2.7

---

.tile/scripts/master.sh

- Adds logic to tile offering installer to check for an existing offering first. If the offering exists it updates the offering with a new version instead of creating a new tile
ibm-garage-cloud/planning#491

Tile offering installer update

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton-resources#60b235dabd3fe27501a0b307fdf33ff9ed8d54a2

Updates ibm-garage-cloud/terraform-tools-tekton-resources module to v2.2.8

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton-resources#ea52bd740e5e545c41fb447bfc5982a6f4c3302d

Updates ibm-garage-cloud/terraform-tools-tekton-resources module to v2.2.9

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton-resources#f41ead061398ee768e6fa4eff1f685c27841cd5b

Updates ibm-garage-cloud/terraform-tools-tekton-resources module to v2.2.10

---

.tile/tiles/cloudnative-toolkit-all-in-one/README.md
.tile/tiles/cloudnative-toolkit-all-in-one/offering.json
.tile/tiles/cluster-vpc/README.md
.tile/tiles/cluster-vpc/offering.json
terraform/settings/environment-ibmcloud.tfvars
terraform/stages-cluster/stage1-cluster.tf
terraform/stages-cluster/variables.tf
terraform/stages/stage1-cluster.tf
terraform/stages/variables.tf

ibm-garage-cloud/terraform-ibm-container-platform#9c20b208289b6ebcf850470d7face375d64407a6

Updates ibm-garage-cloud/terraform-ibm-container-platform module to v1.20.0

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

ibm-garage-cloud/terraform-ibm-image-registry#8b71622127df693e4c49d90efad3de3da0e8b00f

Updates ibm-garage-cloud/terraform-ibm-image-registry module to v1.3.3

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

ibm-garage-cloud/terraform-ocp-image-registry#dc931aa08385e7635034ff2087ed1025ea8428ec

Updates ibm-garage-cloud/terraform-ocp-image-registry module to v1.3.0

---

terraform/stages-sre/stage-activity-tracker.tf

ibm-garage-cloud/terraform-ibm-activity-tracker#987251089cfe76db1dd9cefd695c0ca8c2a91c8d

Updates ibm-garage-cloud/terraform-ibm-activity-tracker module to v1.1.3

---

terraform/stages-sre/stage-activity-tracker.tf

ibm-garage-cloud/terraform-ibm-activity-tracker#6c04e2731184e5324256c2d4ee04ba3e29a5cb6a

Updates ibm-garage-cloud/terraform-ibm-activity-tracker module to v1.1.4

---

terraform/stages-cluster/stage1-cluster.tf
terraform/stages/stage1-cluster.tf

ibm-garage-cloud/terraform-ibm-container-platform#ea7bf70f90b79181aab6fcdfa962329ff07c189f

Updates ibm-garage-cloud/terraform-ibm-container-platform module to v1.20.1

---

terraform/stages-ocp4/stage1-cluster.tf

ibm-garage-cloud/terraform-k8s-ocp-cluster#c22577de6394c5969375f883fd1e1e27f209f990

Updates ibm-garage-cloud/terraform-k8s-ocp-cluster module to v2.4.2

---

terraform/stages-ocp4/stage1-cluster.tf

ibm-garage-cloud/terraform-k8s-ocp-cluster#ed588113a6da00fed38332966473177c14882a37

Updates ibm-garage-cloud/terraform-k8s-ocp-cluster module to v2.4.3

---

terraform/stages-ocp4/stage1-cluster.tf

ibm-garage-cloud/terraform-k8s-ocp-cluster#2ca46b408ca719573709d81554dd230079c97994

Updates ibm-garage-cloud/terraform-k8s-ocp-cluster module to v2.4.4

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton#bcc7d72b83e789ade5048266613fed9a0fdc9098

Updates ibm-garage-cloud/terraform-tools-tekton module to v2.1.1

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

ibm-garage-cloud/terraform-ibm-image-registry#228f166f8f8affa9fa9e48f8a715db75d44a82d8

Updates ibm-garage-cloud/terraform-ibm-image-registry module to v1.3.4

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

ibm-garage-cloud/terraform-ibm-image-registry#51fa4c3d5c889a7be9cb07021d1e5ec4b3a1f2c7

Updates ibm-garage-cloud/terraform-ibm-image-registry module to v1.3.5

---

terraform/stages-ocp4/stage2-sourcecontrol.tf
terraform/stages/stage2-sourcecontrol.tf

ibm-garage-cloud/terraform-k8s-source-control#df6bb913dc59bfe0dff51695c3a7bc9b73dd0273

Updates ibm-garage-cloud/terraform-k8s-source-control module to v1.2.2

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

ibm-garage-cloud/terraform-ibm-image-registry#5e320e6df9cedbbde1fc4bf7539c6a2feabfec88

Updates ibm-garage-cloud/terraform-ibm-image-registry module to v1.3.6

---

terraform/stages-ocp4/stage1-namespaces.tf
terraform/stages/stage1-namespaces.tf

ibm-garage-cloud/terraform-k8s-namespace#0dd1c1ca8485cf9364193bfc445ed45c33015168

Updates ibm-garage-cloud/terraform-k8s-namespace module to v2.7.1

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

ibm-garage-cloud/terraform-ocp-image-registry#8d9699410677daf11d2c89960c089841a14410d1

Updates ibm-garage-cloud/terraform-ocp-image-registry module to v1.3.4

---

terraform/stages-ocp4/stage2-dashboard.tf
terraform/stages/stage2-dashboard.tf

ibm-garage-cloud/terraform-tools-dashboard#8176f4214c8a0ab95f0b9396645e71f4ade5898b

Updates ibm-garage-cloud/terraform-tools-dashboard module to v1.10.5

---

terraform/stages-ocp4/stage2-dashboard.tf
terraform/stages/stage2-dashboard.tf

ibm-garage-cloud/terraform-tools-dashboard#ffc90c83c30d41ba5f37741cea18ada16b6d534d

Updates ibm-garage-cloud/terraform-tools-dashboard module to v1.10.6

---

terraform/stages-ocp4/stage2-artifactory.tf
terraform/stages/stage2-artifactory.tf

ibm-garage-cloud/terraform-tools-artifactory#f9789df3c9be15c19ab717ef59afd8cf77e5d9b6

Updates ibm-garage-cloud/terraform-tools-artifactory module to v1.10.1

---

terraform/stages-cluster/stage1-cluster.tf
terraform/stages/stage1-cluster.tf

ibm-garage-cloud/terraform-ibm-container-platform#ef7e9c5b1fbce99d43c933e0ac684b0e01781c1b

Updates ibm-garage-cloud/terraform-ibm-container-platform module to v1.20.7

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

ibm-garage-cloud/terraform-k8s-image-registry#454d17d9fb0b4344bcc8d2ae153da7d8a58362cf

Updates ibm-garage-cloud/terraform-k8s-image-registry module to v1.1.7

---

terraform/stages-ocp4/stage2-sourcecontrol.tf
terraform/stages/stage2-sourcecontrol.tf

ibm-garage-cloud/terraform-k8s-source-control#47376e658ea30e559d3633faa0ebd09cadc3fb9c

Updates ibm-garage-cloud/terraform-k8s-source-control module to v1.2.3

---

terraform/stages-ocp4/stage1-olm.tf
terraform/stages/stage1-olm.tf

ibm-garage-cloud/terraform-k8s-olm#269e9cfadf1985d815ec243d3365d221c51b01da

Updates ibm-garage-cloud/terraform-k8s-olm module to v1.2.3

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton-resources#22adc8cef5c8db019913d5bd93a205afd45f436b

Updates ibm-garage-cloud/terraform-tools-tekton-resources module to v2.2.11

---

terraform/stages-ocp4/stage1-namespaces.tf
terraform/stages/stage1-namespaces.tf

ibm-garage-cloud/terraform-k8s-namespace#9c14aee6d70cd8d4f5bc9896d981a53defd2e9ea

Updates ibm-garage-cloud/terraform-k8s-namespace module to v2.7.2

---

terraform/stages-ocp4/stage2-dashboard.tf
terraform/stages/stage2-dashboard.tf

ibm-garage-cloud/terraform-tools-dashboard#4141e516bc0b7f97010853cfd786ffbc5180b615

Updates ibm-garage-cloud/terraform-tools-dashboard module to v1.10.7

---

terraform/stages-ocp4/stage2-dashboard.tf
terraform/stages/stage2-dashboard.tf

ibm-garage-cloud/terraform-tools-dashboard#4041e44d2ce34631824b61a4d101a2fbf96978af

Updates ibm-garage-cloud/terraform-tools-dashboard module to v1.10.8

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

ibm-garage-cloud/terraform-ibm-image-registry#07bea4959a4a009a646b1148e16f5d8de62956cb

Updates ibm-garage-cloud/terraform-ibm-image-registry module to v1.4.0

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

ibm-garage-cloud/terraform-ocp-image-registry#1ba47d73fb4aa212d64d330e491a8c74ae457f71

Updates ibm-garage-cloud/terraform-ocp-image-registry module to v1.4.0

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton-resources#210e182500f9f5855852da6aedf1329abf186a36

Updates ibm-garage-cloud/terraform-tools-tekton-resources module to v2.2.12

---

.github/workflows/create-pr.yaml

Adds signoff flag to create-pr to pass validation

---

terraform/stages-cluster/stage1-cluster.tf
terraform/stages/stage1-cluster.tf

ibm-garage-cloud/terraform-ibm-container-platform#d94217eef2750b016e94e06d4c437b15ebb8d782

Updates ibm-garage-cloud/terraform-ibm-container-platform module to v1.20.8

---

.github/scripts/validate-deploy.sh
.github/workflows/verify-master.yaml
.github/workflows/verify-pr.yaml
README.md

Updates verify-pr logic

---

README.md

Updates badge path in README

---

.github/workflows/verify-master.yaml
README.md

Generates last run badge

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

ibm-garage-cloud/terraform-tools-tekton#f78d51dd93f7436f70fa23937c69dd3375c03a7a

Updates ibm-garage-cloud/terraform-tools-tekton module to v2.1.2

---

terraform/stages-sre/stage-key-protect.tf

ibm-garage-cloud/terraform-ibm-key-protect#8a3199332c0ed6ff97fa1089b07d9785b6685f6a

Updates ibm-garage-cloud/terraform-ibm-key-protect module to v1.3.2

---

terraform/stages-sre/stage-object_storage.tf

ibm-garage-cloud/terraform-ibm-object-storage#6295206a702ac23e0d87c031fee6001702793523

Updates ibm-garage-cloud/terraform-ibm-object-storage module to v2.0.2

---

terraform/stages-ocp4/stage0.tf
terraform/stages/stage0.tf

Pins helm provider version to 2.1.1

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

cloud-native-toolkit/terraform-tools-tekton-resources#71b97f74c743e2b8fa1f6381c3c6433d94c65432

Updates cloud-native-toolkit/terraform-tools-tekton-resources module to v2.2.17

---

terraform/stages-ocp4/stage2-argocd.tf
terraform/stages/stage2-argocd.tf

cloud-native-toolkit/terraform-tools-argocd#30c2ff772b64e99460772154dbb21e225e578943

Updates cloud-native-toolkit/terraform-tools-argocd module to v2.11.1

---

terraform/stages-ocp4/stage1-olm.tf
terraform/stages/stage1-olm.tf

cloud-native-toolkit/terraform-k8s-olm#b2d0835efd1fa7df5fe06b3a729fd49a2fe41809

Updates cloud-native-toolkit/terraform-k8s-olm module to v1.2.5

---

terraform/stages-ocp4/stage1-olm.tf
terraform/stages/stage1-olm.tf

cloud-native-toolkit/terraform-k8s-olm#22b7c52a69e737576e4832361d1556306f8976f7

Updates cloud-native-toolkit/terraform-k8s-olm module to v1.2.6

---

terraform/stages-ocp4/stage2-dashboard.tf
terraform/stages/stage2-dashboard.tf

cloud-native-toolkit/terraform-tools-dashboard#802089423aefebee82bf145b4aeffc6bbef056aa

Updates cloud-native-toolkit/terraform-tools-dashboard module to v1.10.12

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

cloud-native-toolkit/terraform-tools-tekton-resources#33dddae00ca9e3d7a8075dba69146d01cfbcf9ba

Updates cloud-native-toolkit/terraform-tools-tekton-resources module to v2.2.20

---

terraform/stages-resource-group/stage-resource-group.tf

cloud-native-toolkit/terraform-ibm-resource-group#791038cb96404e046f9ca1b88220eb696271eb52

Updates cloud-native-toolkit/terraform-ibm-resource-group module to v2.3.0

---

terraform/stages-access-group/stage-access-group.tf

cloud-native-toolkit/terraform-ibm-access-group#e50299fd3b5c60a1224209a3e2859145da004c51

Updates cloud-native-toolkit/terraform-ibm-access-group module to v2.2.0

---

terraform/stages-ocp4/stage1-olm.tf
terraform/stages/stage1-olm.tf

cloud-native-toolkit/terraform-k8s-olm#66fe6e6beaffd604120a0fc8f03003ebeee1d235

Updates cloud-native-toolkit/terraform-k8s-olm module to v1.3.0

---

terraform/stages-ocp4/stage2-argocd.tf
terraform/stages/stage2-argocd.tf

cloud-native-toolkit/terraform-tools-argocd#f60f95150020a601344b53c57f735d9bdc4eaa59

Updates cloud-native-toolkit/terraform-tools-argocd module to v2.12.0

---

terraform/stages-ocp4/stage2-argocd.tf
terraform/stages/stage2-argocd.tf

cloud-native-toolkit/terraform-tools-argocd#f734b92a050faf3f301b7ab5aa34c86fcc0a9207

Updates cloud-native-toolkit/terraform-tools-argocd module to v2.12.1

---

terraform/stages-sre/stage-object_storage.tf

cloud-native-toolkit/terraform-ibm-object-storage#a0941fbdc65e57db70428f957c2ef16f0a8f8520

Updates cloud-native-toolkit/terraform-ibm-object-storage module to v3.3.0

---

terraform/stages-sre/stage-object_storage.tf

cloud-native-toolkit/terraform-ibm-object-storage#e66e3f3daa65593142b1eb34ab0fc56b8e7788dd

Updates cloud-native-toolkit/terraform-ibm-object-storage module to v3.3.2

---

terraform/stages-ocp4/stage2-argocd.tf
terraform/stages/stage2-argocd.tf

cloud-native-toolkit/terraform-tools-argocd#e02da3c5377eb64004ba6c927efc83238755fff8

Updates cloud-native-toolkit/terraform-tools-argocd module to v2.13.0

---

terraform/stages-ocp4/stage1-namespaces.tf
terraform/stages/stage1-namespaces.tf

cloud-native-toolkit/terraform-k8s-namespace#9dd3d8b46b9ac9fbff3006afbcbb91c6e3ed17ba

Updates cloud-native-toolkit/terraform-k8s-namespace module to v2.8.1

---

terraform/stages-ocp4/stage2-argocd.tf
terraform/stages/stage2-argocd.tf

cloud-native-toolkit/terraform-tools-argocd#1419454223abdf75e372d7f4b82bde777a1e288c

Updates cloud-native-toolkit/terraform-tools-argocd module to v2.13.1

---

terraform/stages-ocp4/stage1-olm.tf
terraform/stages/stage1-olm.tf

cloud-native-toolkit/terraform-k8s-olm#f482e6be79328604368580b1ec2d7a08b840f674

Updates cloud-native-toolkit/terraform-k8s-olm module to v1.3.1

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

cloud-native-toolkit/terraform-tools-tekton#a1d7128d9c6977618c55fb795575f9c97062e35f

Updates cloud-native-toolkit/terraform-tools-tekton module to v2.2.0

---

terraform/stages-ocp4/stage2-argocd.tf
terraform/stages/stage2-argocd.tf

cloud-native-toolkit/terraform-tools-argocd#638db898b0ed940fa909f49a47121a19cc98bcb7

Updates cloud-native-toolkit/terraform-tools-argocd module to v2.14.0

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

cloud-native-toolkit/terraform-tools-tekton#48efe1822ae926c795306dc74409d090aca22cca

Updates cloud-native-toolkit/terraform-tools-tekton module to v2.2.1

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-cicd.tf
terraform/stages/stage2-pipelines.tf

Replaces argocd and tekton modules with openshift-cicd

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#d511525946cd58ac8ffa0dedc95a117827a0cd6d

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.1.0

---

terraform/stages-access-group/stage-access-group.tf

cloud-native-toolkit/terraform-ibm-access-group#cfd648e5d92d715cb71dd265f151dbe8b2d33452

Updates cloud-native-toolkit/terraform-ibm-access-group module to v2.3.0

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#b912ba44be91fc96096459b211adce7dd1519528

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.2.0

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#acf1889cd051c68e55d08fd3e868dab67663fda2

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.2.1

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#810301d47ffe1592e778bf07f3737c7c56637d3b

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.2.2

---

terraform/stages/stage2-jenkins.tf

cloud-native-toolkit/terraform-tools-jenkins#c3efd54f25e51811023400af42f577d13f05238d

Updates cloud-native-toolkit/terraform-tools-jenkins module to v1.4.4

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#1571552dd56c4fd01411c52920a18b5a0664cbba

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.5.0

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#23ae8d1b3ae34c8edd687ff2b284122794e33db1

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.5.1

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#22a0f6c8eab44a1f970c0cd34e77a079671e0b89

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.5.5

---

terraform/stages-ocp4/stage2-dashboard.tf
terraform/stages/stage2-dashboard.tf

cloud-native-toolkit/terraform-tools-dashboard#46fbd3b78adaa37d9e8d6642c3852a075702eb2a

Updates cloud-native-toolkit/terraform-tools-dashboard module to v1.10.13

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

cloud-native-toolkit/terraform-tools-tekton-resources#29734ff555efd57304dd8db1ff7036b01f07d8f8

Updates cloud-native-toolkit/terraform-tools-tekton-resources module to v2.2.21

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

cloud-native-toolkit/terraform-tools-tekton-resources#5dad176687e93710ab15ac21ac884e3411a9775e

Updates cloud-native-toolkit/terraform-tools-tekton-resources module to v2.2.22

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#fa561b1a615b029c3a771ab7e12a6e4e1aa2c26f

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.7.1

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#e7e62691f952cb7fefe6e9b968b03c34bca6c637

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.7.2

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#6f0f401de63932873e3f45104acff1ccf416a789

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.7.5

---

terraform/stages-sre/stage-logdna.tf
terraform/stages/stage3-logdna.tf

cloud-native-toolkit/terraform-ibm-logdna#b8ab87d4298f766cec8e5093089f7638565cd3c5

Updates cloud-native-toolkit/terraform-ibm-logdna module to v4.0.0

---

terraform/stages-sre/stage-sysdig.tf
terraform/stages/stage3-sysdig.tf

cloud-native-toolkit/terraform-ibm-sysdig#22c83a0770b16e68e72469f7bdc8392f3f62871b

Updates cloud-native-toolkit/terraform-ibm-sysdig module to v4.0.1

---

terraform/stages-sre/stage-activity-tracker.tf

cloud-native-toolkit/terraform-ibm-activity-tracker#b9442543045d3915df2855649b09b33e8fa088fd

Updates cloud-native-toolkit/terraform-ibm-activity-tracker module to v2.4.0

---

terraform/stages-sre/stage-key-protect.tf

cloud-native-toolkit/terraform-ibm-key-protect#764ae124038e42b487b7f578a779b3aabff23eff

Updates cloud-native-toolkit/terraform-ibm-key-protect module to v2.3.0

---

terraform/stages-resource-group/stage-resource-group.tf

cloud-native-toolkit/terraform-ibm-resource-group#24783f774daad95016a4385206a65a1706226394

Updates cloud-native-toolkit/terraform-ibm-resource-group module to v3.0.1

---

terraform/stages-sre/stage-object_storage.tf

cloud-native-toolkit/terraform-ibm-object-storage#5a11fdcf68b18d0b52f74ea3b515c3e669e11840

Updates cloud-native-toolkit/terraform-ibm-object-storage module to v4.0.0

---

terraform/stages-ocp4/stage1-cluster.tf

cloud-native-toolkit/terraform-k8s-ocp-cluster#d4a484ac9796ec60b12be61cd1305f6162a247e6

Updates cloud-native-toolkit/terraform-k8s-ocp-cluster module to v2.4.5

---

terraform/stages-ocp4/stage1-olm.tf
terraform/stages/stage1-olm.tf

cloud-native-toolkit/terraform-k8s-olm#73bd741218a41dd6e33d5932810db95a8f12de3b

Updates cloud-native-toolkit/terraform-k8s-olm module to v1.3.2

---

terraform/stages-ocp4/stage2-sourcecontrol.tf
terraform/stages/stage2-sourcecontrol.tf

cloud-native-toolkit/terraform-k8s-source-control#aec3fb6c2d73f801cd7f71ab718eee552a55a30a

Updates cloud-native-toolkit/terraform-k8s-source-control module to v1.3.1

---

terraform/stages-ocp4/stage2-swagger-editor.tf
terraform/stages/stage2-swagger.tf

cloud-native-toolkit/terraform-tools-swaggereditor#6b24800bd28695ea14845924949bdb4ee3a75b70

Updates cloud-native-toolkit/terraform-tools-swaggereditor module to v1.5.1

---

terraform/stages-ocp4/stage2-pactbroker.tf
terraform/stages/stage2-pactbroker.tf

cloud-native-toolkit/terraform-tools-pactbroker#19aa2f07e6c451d0eb7c316c0b0196866200fbd0

Updates cloud-native-toolkit/terraform-tools-pactbroker module to v1.5.1

---

terraform/stages-ocp4/stage2-artifactory.tf
terraform/stages/stage2-artifactory.tf

cloud-native-toolkit/terraform-tools-artifactory#74fb37149bc536d36d5c448c2dbae277eefec7d7

Updates cloud-native-toolkit/terraform-tools-artifactory module to v1.12.2

---

.github/scripts/validate-deploy.sh
.github/workflows/verify-pr.yaml
terraform/stages-ocp4/stage1-cluster.tf
terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages-ocp4/stage2-sonarqube.tf
terraform/stages-ocp4/variables.tf
terraform/stages/stage1-cluster.tf

Adds stages-ocp4 to test matrix

---

terraform/stages-ocp4/stage2-sonarqube.tf
terraform/stages/stage2-sonarqube.tf

cloud-native-toolkit/terraform-tools-sonarqube#7830114345424aff94f234ce597d2472f8c23e88

Updates cloud-native-toolkit/terraform-tools-sonarqube module to v1.10.0

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

cloud-native-toolkit/terraform-ibm-image-registry#8cd6549b3a80f7684d8546950dca00eadb3a0902

Updates cloud-native-toolkit/terraform-ibm-image-registry module to v2.1.1

---

terraform/stages/stage3-sysdig-bind.tf

cloud-native-toolkit/terraform-ibm-sysdig-bind#e26c7a9c69b9b8f348191e3cc5be1ee56084cdef

Updates cloud-native-toolkit/terraform-ibm-sysdig-bind module to v1.2.3

---

terraform/stages/stage3-logdna-bind.tf

cloud-native-toolkit/terraform-ibm-logdna-bind#4b51f34a91658a2d114fe86b3ee7e082391b1720

Updates cloud-native-toolkit/terraform-ibm-logdna-bind module to v1.2.2

---

terraform/stages-ocp4/stage1-cluster.tf

cloud-native-toolkit/terraform-k8s-ocp-cluster#957adfc0eb5ef3439685ecd73f7b8011e4880779

Updates cloud-native-toolkit/terraform-k8s-ocp-cluster module to v2.4.6

---

terraform/stages-ocp4/stage2-sonarqube.tf
terraform/stages/stage2-sonarqube.tf

cloud-native-toolkit/terraform-tools-sonarqube#3d868dfd417a65dd13b9f29d529655d7663eae18

Updates cloud-native-toolkit/terraform-tools-sonarqube module to v1.10.1

---

terraform/stages-ocp4/stage2-dashboard.tf
terraform/stages/stage2-dashboard.tf

cloud-native-toolkit/terraform-tools-dashboard#3b17c71e947cd99b4d126564efe52d6c9d9f1bd9

Updates cloud-native-toolkit/terraform-tools-dashboard module to v1.10.14

---

terraform/stages-ocp4/stage2-pactbroker.tf
terraform/stages/stage2-pactbroker.tf

cloud-native-toolkit/terraform-tools-pactbroker#c61fdb87e12afd6dc647b1eabd17a5e9e1a121c7

Updates cloud-native-toolkit/terraform-tools-pactbroker module to v1.5.3

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#4de5eaa3b87aa6a2b820834ea2368e8d83900391

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.7.7

---

.github/workflows/verify-master.yaml
.github/workflows/verify-pr.yaml
terraform/stages-ocp4/stage1-cluster.tf
terraform/stages-ocp4/stage1-namespaces.tf
terraform/stages-ocp4/stage2-cicd.tf
terraform/stages-ocp4/stage2-console-link-job.tf
terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages-ocp4/stage2-pactbroker.tf
terraform/stages-ocp4/stage2-sonarqube.tf
terraform/stages/stage1-namespaces.tf
terraform/stages/stage2-cicd.tf

fixes https://github.com/cloud-native-toolkit/planning/issues/916

Version updates

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#21c5e727183f96726ad7a59ea52e04e7a9c5b7dc

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.10.1

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#cfde2d7a919cd03ce5451bddc3cb772f12421dde

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.10.2

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

cloud-native-toolkit/terraform-ibm-image-registry#5d792af0f360511adc669db1ffd103c99478a7d7

Updates cloud-native-toolkit/terraform-ibm-image-registry module to v2.1.3

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#960cb99a8e27bcf689783e20a21d61567bea2214

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.10.4

---

terraform/stages-ocp4/stage1-namespaces.tf
terraform/stages/stage1-namespaces.tf

cloud-native-toolkit/terraform-k8s-namespace#8879666310ef378241d9d8097a02b0e762e2b75e

Updates cloud-native-toolkit/terraform-k8s-namespace module to v3.2.3

---

terraform/stages-ocp4/stage2-cicd.tf
terraform/stages/stage2-cicd.tf

cloud-native-toolkit/terraform-tools-openshift-cicd#179574de24b7677be2211ae68209427a88ee4de1

Updates cloud-native-toolkit/terraform-tools-openshift-cicd module to v1.11.0

---

terraform/stages-ocp4/stage2-pipelines.tf
terraform/stages/stage2-pipelines.tf

cloud-native-toolkit/terraform-tools-tekton-resources#446f2062cbab14a564f0701d49eafa3569ef99d5

Updates cloud-native-toolkit/terraform-tools-tekton-resources module to v2.3.2

---

terraform/stages-ocp4/stage2-image-registry.tf
terraform/stages/stage2-image-registry.tf

cloud-native-toolkit/terraform-ibm-image-registry#91bf31d6b02afbfa5aba1aeace7506b17a4d72e2

Updates cloud-native-toolkit/terraform-ibm-image-registry module to v2.1.4

---

.github/workflows/publish.yaml

Publishes install script to gh-pages
